import { PatientRecord } from "@/types/patient";

// 開発・API障害時のフォールバック用モックデータ。
// 実データの癖（MM-DD表記・年跨ぎの負値在院日数・日英混在の転帰・欠損）と
// 研究用追加項目（列28以降）を網羅し、全タブ・全統計を offline で確認できる。
const MOCK_PATIENTS: PatientRecord[] = [
    {
        timestamp: "2023/10/01 10:00:00",
        id: "P001",
        gender: "女性",
        age: 82,
        injuryDate: "2023/09/25",
        fallHistory: "転倒あり",
        preInjuryADL: "Independent",
        neuroSymptoms: "None",
        ofClassification: "Type 3",
        mriImage: "https://example.com/mri/p001.png",
        medicalHistory: "Hypertension",
        osteoporosisHistory: "Alendronate",
        remarks: "体動時痛強い",
        currentPain: "Severe",
        admissionDate: "2023/10/01",
        newFractures: "L1",
        timeToAdmission: "6 days",
        outcome: "手術",
        procedure: "BKP",
        surgeryDate: "2023/10/02",
        dischargeDate: "2023/10/20",
        hospitalizationPeriod: "19",
        height: 148,
        weight: 42,
        dischargeDestination: "自宅",
        followUpStatus: "Discharged",
        bmdYamPercent: 62,
        bmdTScore: -3.1,
        nrsOnAdmission: 8,
        nrsAtDischarge: 3,
        barthelOnAdmission: 65,
        barthelAtDischarge: 85,
        ambulationAtDischarge: "独歩",
        albumin: 3.6,
        vitD25OH: 14,
        complications: "なし",
        adjacentFracture: "なし",
        readmission90d: "なし",
        deathStatus: "なし",
        braceType: "軟性",
        opMedAtDischarge: "テリパラチド",
    },
    {
        timestamp: "2023/10/05 14:30:00",
        id: "P002",
        gender: "男性",
        age: 75,
        injuryDate: "2023/10/03",
        fallHistory: "No",
        preInjuryADL: "Assisted",
        neuroSymptoms: "Radiculopathy",
        ofClassification: "Type 4",
        mriImage: "T12 collapse",
        medicalHistory: "Diabetes",
        osteoporosisHistory: "None",
        remarks: "神経症状あり手術検討",
        currentPain: "Moderate",
        admissionDate: "2023/10/05",
        newFractures: "T12",
        timeToAdmission: "2 days",
        outcome: "Surgery",
        procedure: "BKP+PF",
        surgeryDate: "2023/10/10",
        dischargeDate: "2023/11/02",
        hospitalizationPeriod: "28",
        height: 162,
        weight: 58,
        dischargeDestination: "リハビリ転院",
        followUpStatus: "Discharged",
        bmdYamPercent: 68,
        bmdTScore: -2.8,
        nrsOnAdmission: 7,
        nrsAtDischarge: 2,
        barthelOnAdmission: 40,
        barthelAtDischarge: 70,
        ambulationAtDischarge: "杖",
        albumin: 3.9,
        vitD25OH: 18,
        complications: "せん妄",
        adjacentFracture: "なし",
        readmission90d: "なし",
        deathStatus: "なし",
        braceType: "硬性",
        opMedAtDischarge: "デノスマブ",
    },
    {
        timestamp: "2023/11/10 09:15:00",
        id: "P003",
        gender: "女性",
        age: 88,
        injuryDate: "2023/11/08",
        fallHistory: "転倒あり",
        preInjuryADL: "Wheelchair",
        neuroSymptoms: "None",
        ofClassification: "Type 2",
        mriImage: "L3 edema",
        medicalHistory: "Dementia",
        osteoporosisHistory: "Denosumab",
        remarks: "保存的に加療",
        currentPain: "Mild",
        admissionDate: "2023/11/10",
        newFractures: "L3",
        timeToAdmission: "2 days",
        outcome: "保存",
        procedure: "",
        surgeryDate: "",
        dischargeDate: "2023/11/24",
        hospitalizationPeriod: "14 days",
        height: 145,
        weight: 38,
        dischargeDestination: "施設",
        followUpStatus: "Discharged",
        bmdYamPercent: 58,
        bmdTScore: -3.4,
        nrsOnAdmission: 6,
        nrsAtDischarge: 3,
        barthelOnAdmission: 50,
        barthelAtDischarge: 60,
        ambulationAtDischarge: "車椅子",
        albumin: 3.2,
        vitD25OH: 9,
        complications: "尿路感染",
        adjacentFracture: "なし",
        readmission90d: "なし",
        deathStatus: "なし",
        braceType: "硬性",
        opMedAtDischarge: "デノスマブ",
    },
    {
        timestamp: "2023/11/15 11:00:00",
        id: "P004",
        gender: "女性",
        age: 79,
        injuryDate: "2023/11/13",
        fallHistory: "転倒あり",
        preInjuryADL: "Independent",
        neuroSymptoms: "None",
        ofClassification: "Type 3",
        mriImage: "T11 fresh fracture",
        medicalHistory: "None",
        osteoporosisHistory: "None",
        remarks: "経過観察中",
        currentPain: "Severe",
        admissionDate: "2023/11/15",
        newFractures: "T11",
        timeToAdmission: "2 days",
        outcome: "経過観察",
        procedure: "",
        surgeryDate: "",
        dischargeDate: "",
        hospitalizationPeriod: "",
        dischargeDestination: "",
        followUpStatus: "In Hospital",
        nrsOnAdmission: 7,
        barthelOnAdmission: 55,
    },
    {
        // 年跨ぎケース: 12/25入院→翌1/10退院、シート計算が負値(-350)を返した想定。
        // 在院日数は日付から16日に再計算される
        timestamp: "2024/01/05 16:20:00",
        id: "P005",
        gender: "男性",
        age: 84,
        injuryDate: "12-20",
        fallHistory: "転倒あり",
        preInjuryADL: "Independent",
        neuroSymptoms: "None",
        ofClassification: "Type 3",
        mriImage: "L2 high intensity",
        medicalHistory: "Hypertension, CKD",
        osteoporosisHistory: "None",
        remarks: "",
        currentPain: "Severe",
        admissionDate: "12-25",
        newFractures: "L2",
        timeToAdmission: "5 days",
        outcome: "手術",
        procedure: "BKP",
        surgeryDate: "01-04",
        dischargeDate: "01-10",
        hospitalizationPeriod: "-350",
        height: 158,
        weight: 52,
        dischargeDestination: "自宅",
        followUpStatus: "Discharged",
        bmdYamPercent: 55,
        bmdTScore: -3.6,
        nrsOnAdmission: 9,
        nrsAtDischarge: 4,
        barthelOnAdmission: 30,
        barthelAtDischarge: 55,
        ambulationAtDischarge: "歩行器",
        albumin: 3.0,
        vitD25OH: 7,
        complications: "肺炎, せん妄",
        adjacentFracture: "あり",
        readmission90d: "あり",
        deathStatus: "なし",
        braceType: "硬性",
        opMedAtDischarge: "ロモソズマブ",
    },
    {
        timestamp: "2024/02/12 08:45:00",
        id: "P006",
        gender: "女性",
        age: 91,
        injuryDate: "2024/02/08",
        fallHistory: "転倒あり",
        preInjuryADL: "Assisted",
        neuroSymptoms: "None",
        ofClassification: "Type 4",
        mriImage: "T12, L1 collapse",
        medicalHistory: "Dementia, CHF",
        osteoporosisHistory: "None",
        remarks: "多発骨折",
        currentPain: "Moderate",
        admissionDate: "2024/02/12",
        newFractures: "T12, L1",
        timeToAdmission: "4 days",
        outcome: "保存的加療",
        procedure: "",
        surgeryDate: "",
        dischargeDate: "2024/03/28",
        hospitalizationPeriod: "45",
        height: 142,
        weight: 36,
        dischargeDestination: "施設",
        followUpStatus: "Discharged",
        bmdYamPercent: 52,
        bmdTScore: -3.9,
        nrsOnAdmission: 7,
        nrsAtDischarge: 5,
        barthelOnAdmission: 35,
        barthelAtDischarge: 40,
        ambulationAtDischarge: "車椅子",
        albumin: 2.8,
        vitD25OH: 6,
        complications: "肺炎, 褥瘡",
        adjacentFracture: "あり",
        readmission90d: "なし",
        deathStatus: "1年以内",
        braceType: "軟性",
        opMedAtDischarge: "なし",
    },
    {
        timestamp: "2024/03/03 13:10:00",
        id: "P007",
        gender: "女性",
        age: 73,
        injuryDate: "2024/03/01",
        fallHistory: "転倒あり",
        preInjuryADL: "Independent",
        neuroSymptoms: "None",
        ofClassification: "Type 2",
        mriImage: "L4 edema",
        medicalHistory: "None",
        osteoporosisHistory: "Alendronate",
        remarks: "",
        currentPain: "Mild",
        admissionDate: "2024/03/03",
        newFractures: "L4",
        timeToAdmission: "2 days",
        outcome: "保存",
        procedure: "",
        surgeryDate: "",
        dischargeDate: "2024/03/17",
        hospitalizationPeriod: "14",
        height: 152,
        weight: 48,
        dischargeDestination: "自宅",
        followUpStatus: "Discharged",
        bmdYamPercent: 71,
        bmdTScore: -2.4,
        nrsOnAdmission: 5,
        nrsAtDischarge: 1,
        barthelOnAdmission: 80,
        barthelAtDischarge: 95,
        ambulationAtDischarge: "独歩",
        albumin: 4.0,
        vitD25OH: 22,
        complications: "なし",
        adjacentFracture: "なし",
        readmission90d: "なし",
        deathStatus: "なし",
        braceType: "軟性",
        opMedAtDischarge: "アレンドロネート",
    },
    {
        timestamp: "2024/04/18 10:30:00",
        id: "P008",
        gender: "男性",
        age: 68,
        injuryDate: "2024/04/15",
        fallHistory: "高エネルギー外傷",
        preInjuryADL: "Independent",
        neuroSymptoms: "None",
        ofClassification: "Type 4",
        mriImage: "L1 burst",
        medicalHistory: "None",
        osteoporosisHistory: "None",
        remarks: "脚立から転落",
        currentPain: "Severe",
        admissionDate: "2024/04/18",
        newFractures: "L1",
        timeToAdmission: "3 days",
        outcome: "手術",
        procedure: "BKP+PF",
        surgeryDate: "2024/04/25",
        dischargeDate: "2024/05/20",
        hospitalizationPeriod: "32",
        height: 168,
        weight: 65,
        dischargeDestination: "自宅",
        followUpStatus: "Discharged",
        bmdYamPercent: 66,
        bmdTScore: -2.9,
        nrsOnAdmission: 8,
        nrsAtDischarge: 2,
        barthelOnAdmission: 55,
        barthelAtDischarge: 80,
        ambulationAtDischarge: "杖",
        albumin: 4.2,
        vitD25OH: 25,
        complications: "DVT",
        adjacentFracture: "なし",
        readmission90d: "なし",
        deathStatus: "なし",
        braceType: "硬性",
        opMedAtDischarge: "テリパラチド",
    },
    {
        timestamp: "2024/05/22 09:00:00",
        id: "P009",
        gender: "女性",
        age: 86,
        injuryDate: "2024/05/20",
        fallHistory: "転倒あり",
        preInjuryADL: "Independent",
        neuroSymptoms: "None",
        ofClassification: "Type 3",
        mriImage: "https://example.com/mri/p009-1.png https://example.com/mri/p009-2.png",
        medicalHistory: "Hypertension",
        osteoporosisHistory: "Denosumab",
        remarks: "",
        currentPain: "Severe",
        admissionDate: "2024/05/22",
        newFractures: "T8",
        timeToAdmission: "2 days",
        outcome: "手術",
        procedure: "BKP",
        surgeryDate: "2024/05/24",
        dischargeDate: "2024/06/14",
        hospitalizationPeriod: "23",
        height: 146,
        weight: 40,
        dischargeDestination: "リハビリ転院",
        followUpStatus: "Discharged",
        bmdYamPercent: 60,
        bmdTScore: -3.2,
        nrsOnAdmission: 7,
        nrsAtDischarge: 3,
        barthelOnAdmission: 45,
        barthelAtDischarge: 70,
        ambulationAtDischarge: "歩行器",
        albumin: 3.4,
        vitD25OH: 11,
        complications: "なし",
        adjacentFracture: "なし",
        readmission90d: "なし",
        deathStatus: "なし",
        braceType: "軟性",
        opMedAtDischarge: "デノスマブ",
    },
    {
        // 欠損だらけのレコード（外来・転帰未記入）: 空データ耐性の確認用
        timestamp: "2024/06/02 15:40:00",
        id: "P010",
        gender: "女性",
        age: 77,
        injuryDate: "2024/05/30",
        fallHistory: "",
        preInjuryADL: "",
        neuroSymptoms: "",
        ofClassification: "",
        mriImage: "",
        medicalHistory: "",
        osteoporosisHistory: "",
        remarks: "外来フォロー",
        currentPain: "",
        admissionDate: "",
        newFractures: "",
        timeToAdmission: "",
        outcome: "",
        procedure: "",
        surgeryDate: "",
        dischargeDate: "",
        hospitalizationPeriod: "",
        dischargeDestination: "",
        followUpStatus: "Pending",
    },
];

// 任意項目: 空欄・null は undefined に潰し、値があればそのまま通す
const optionalValue = (v: unknown): string | number | undefined => {
    if (v === null || v === undefined) return undefined;
    if (typeof v === "number") return v;
    const s = String(v).trim();
    return s === "" ? undefined : s;
};

const optionalString = (v: unknown): string | undefined => {
    const value = optionalValue(v);
    return value === undefined ? undefined : String(value);
};

export const fetchPatients = async (): Promise<PatientRecord[]> => {
    const apiUrl = process.env.NEXT_PUBLIC_GAS_API_URL || "https://script.google.com/macros/s/AKfycbw0LNnpIRqenWmnWd31Mg2dN6yJ0wXoaGY0KB8Btg1D0WeSYqVnCKiTlb5GiaHcfhD2/exec";

    if (!apiUrl) {
        console.warn("NEXT_PUBLIC_GAS_API_URL is not set. Using mock data.");
        // Return mock data if API URL is not set (for development)
        await new Promise((resolve) => setTimeout(resolve, 500));
        return MOCK_PATIENTS;
    }

    try {
        const response = await fetch(apiUrl, { next: { revalidate: 3600 } }); // page.tsx の revalidate と揃える
        if (!response.ok) {
            throw new Error(`Failed to fetch data: ${response.statusText}`);
        }
        const data = await response.json();

        // Defensive: Sanitize data to ensure it matches the PatientRecord interface
        // This prevents crashes if GAS returns numbers/nulls where strings are expected (e.g. after column shifts)
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const sanitizedData: PatientRecord[] = Array.isArray(data) ? data.map((item: any) => ({
            timestamp: String(item.timestamp || ""),
            id: String(item.id || ""),
            gender: String(item.gender || ""),
            age: Number(item.age) || 0,
            injuryDate: String(item.injuryDate || ""),
            fallHistory: String(item.fallHistory || ""),
            preInjuryADL: String(item.preInjuryADL || ""),
            neuroSymptoms: String(item.neuroSymptoms || ""),
            ofClassification: String(item.ofClassification || ""),
            mriImage: String(item.mriImage || ""),
            medicalHistory: String(item.medicalHistory || ""),
            osteoporosisHistory: String(item.osteoporosisHistory || ""),
            remarks: String(item.remarks || ""),
            currentPain: String(item.currentPain || ""),
            admissionDate: String(item.admissionDate || ""),
            newFractures: String(item.newFractures || ""),
            timeToAdmission: String(item.timeToAdmission || ""),
            outcome: String(item.outcome || ""),
            procedure: String(item.procedure || ""),
            surgeryDate: String(item.surgeryDate || ""),
            dischargeDate: String(item.dischargeDate || ""),
            hospitalizationPeriod: String(item.hospitalizationPeriod || ""),
            height: item.height, // Keep optional/number as is
            weight: item.weight,
            bmi: item.bmi,
            dischargeDestination: String(item.dischargeDestination || ""),
            followUpStatus: String(item.followUpStatus || ""),
            // 研究用の任意項目（列27〜42）。旧GASデプロイではキー自体が無く undefined になる
            remarks2: optionalString(item.remarks2),
            bmdYamPercent: optionalValue(item.bmdYamPercent),
            bmdTScore: optionalValue(item.bmdTScore),
            nrsOnAdmission: optionalValue(item.nrsOnAdmission),
            nrsAtDischarge: optionalValue(item.nrsAtDischarge),
            barthelOnAdmission: optionalValue(item.barthelOnAdmission),
            barthelAtDischarge: optionalValue(item.barthelAtDischarge),
            ambulationAtDischarge: optionalString(item.ambulationAtDischarge),
            albumin: optionalValue(item.albumin),
            vitD25OH: optionalValue(item.vitD25OH),
            complications: optionalString(item.complications),
            adjacentFracture: optionalString(item.adjacentFracture),
            readmission90d: optionalString(item.readmission90d),
            deathStatus: optionalString(item.deathStatus),
            braceType: optionalString(item.braceType),
            opMedAtDischarge: optionalString(item.opMedAtDischarge),
        })) : [];

        return sanitizedData;
    } catch (error) {
        console.error("Error fetching patient data:", error);
        return MOCK_PATIENTS; // Fallback to mock data on error
    }
};
